version: '3.9'

services:

  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"

  webhook-sender:
    build: ../webhook
    environment:
      REDIS_ADDRESS: redis:6379
    depends_on:
      - redis

  flask-api:
    build: ./api/
    ports:
      - "5001:5000"
    depends_on:
      - webhook-sender
